spring:
  application:
    name: EchoLife

  datasource:
    url: jdbc:postgresql://localhost:5432/Echolifebd
    username: postgres
    password: 0885
    driverClassName: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_EMAIL}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

gpt4free:
  api:
    key: ${GPT4FREE_API_KEY}
    url: ${GPT4FREE_API_URL}

